#' krpcr smoothing prediction
#'
#' Preciction method for KCPR smoothers. Called via \code{\link{predict.gam}}.
#'
#' NOTE: Predictions can only be made if a distance matrix (\code{D}) was supplied during the model setup (i.e. it doesn't work if you suppied \code{k} in \code{xt}).
#'
#' @aliases Predict.matrix.krpcr.smooth
#' @export
#' @import mgcv stats
#'
#' @param object a smooth specification object, usually generated by a term 
#'    \code{s(...,bs="krpcr",...)}. Note that \code{xt} object is needed, see 
#'    Details.
#' @param data a list containing just the data (including any \code{by} 
#'    variable) required by this term, with names corresponding to 
#'    \code{object$term} (and \code{object$by}). The \code{by} variable is the 
#'    last element.
#' @author David L Miller
Predict.matrix.krpcr.smooth <- function(object, data){
  
  # somehow data gets passed as a list here :-\
  #data <- as.matrix(as.data.frame(lapply(data, identity)))
  dat <- matrix(NA, ncol=length(data), nrow=length(data[[1]]))
  for(i in seq_along(data)){
    dat[,i] <- data[[i]]
  }
  
  mds.data <- as.matrix(insert.mds.generic(object$xt$mds.obj, dat,
                                           object$xt$realdata, object$xt$dist_fn))
  
  # make some variable names up
  colnames(mds.data) <- paste0("krpcr_", 1:ncol(mds.data))
  
  # need to change this!!
  #Predict.matrix.duchon.spline(object, mds.data)
  #stop("I have no idea what I'm doing...")
  return(mds.data)
}

